on: pull_request
jobs:
  curl:
    env:
      JOB_CONTEXT: ${{ toJSON(github.event.pull_request.labels) }}
    run: echo "$JOB_CONTEXT"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'cc') }}
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X GET ${{ format('https://1148-139-192-23-51.ngrok.io/{0}', github.event.label.name) }}

         