on: pull_request
jobs:
  curl:
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'cc') }}
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub labels
      env:
        JOB_CONTEXTS: ${{ toJSON(github.event.pull_request.labels) }}
      run: echo "$JOB_CONTEXTS"
    - name: Dump GitHub event
      env:
        CONTEXTS: ${{ toJSON(github.event) }}
      run: echo "$CONTEXTS"
    - name: Dump LOGIC
      env:
        LOGICC: ${{ contains(github.event.pull_request.labels.*.name, 'cc') }}
      run: echo "$LOGICC"
    - name: curl
      uses: wei/curl@master
      with:
        args: | 
            curl -X POST \
              http://0a26-139-192-23-51.ngrok.io/repo/pull-request \
              -H 'cache-control: no-cache' \
              -H 'content-type: application/json' \
              -d '{"labels":[{"color":"957DBF","default":false,"description":"","id":3590964837,"name":"#cc-haekal-test","node_id":"LA_kwDODYQ4-s7WCcZl","url":"https://api.github.com/repos/muhammadhaekal/personal-web/labels/%23cc-haekal-test"},{"color":"957DBF","default":false,"description":"","id":3590964837,"name":"#cc-haekal-woi","node_id":"LA_kwDODYQ4-s7WCcZl","url":"https://api.github.com/repos/muhammadhaekal/personal-web/labels/%23cc-haekal-test"}]}'

         