on: pull_request
jobs:
  curl:
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'cc') }}
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub labels
      env:
        JOB_CONTEXTS: ${{ toJSON(github.event.pull_request.labels) }}
      run: echo "$JOB_CONTEXTS"
    - name: Dump GitHub event
      env:
        CONTEXTS: ${{ toJSON(github.event) }}
      run: echo "$CONTEXTS"
    - name: Dump LOGIC
      env:
        LOGICC: ${{ contains(github.event.pull_request.labels.*.name, 'cc') }}
      run: echo "$LOGICC"
    - name: 'Call API'
      uses: actionsflow/axios@v1
      with:
        url: http://e487-139-192-23-51.ngrok.io/repo/pull-request
        method: 'POST'
        accept: 200,201,204
        headers: '{ "Content-Type": "application/json" }'
        data: '{"labels": ${{ toJSON(github.event.pull_request.labels) }},"sender": "${{ github.event.sender.login }}","url":"${{ github.event.pull_request._links.html.href }}","title":"${{ github.event.pull_request.title }}"}'